[project]
name = "rlinit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mujoco>=3.15.0",
    "numpy>=2.5.3",
    "gymnasium>=1.2,<2",
    "stable-baselines3>=2.7,<3",
    "torch>=2.9,<3",
    "matplotlib>=3.11.2",
]

[project.scripts]
rlinit = "rlinit:main"

[project.optional-dependencies]
cpu = ["torch>=2.9,<3"]
cuda = ["torch>=2.9,<3"]

[tool.uv]
conflicts = [[{ extra = "cpu" }, { extra = "cuda" }]]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu128", extra = "cuda" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
